### ISSUE TITLE
when i  executive './build.py --use_ccache' ,i got a error 

### ISSUE THREAD

**Issue by D8Ge** [ry/deno#126]
![2018-06-04 4 20 57](https://user-images.githubusercontent.com/19723961/40906576-ce5a75d8-6813-11e8-8ebc-0e0d58f6e711.png)
i had try all things in [#60](https://github.com/ry/deno/issues/60#issuecomment-393762644)

**Comment by JieJiSS** [comment]
I got the same error and solved it by running
```bash
# I'm using ss as my proxy which is listening on localhost:1087 and 1086
export https_proxy="http://localhost:1087"
export http_proxy="http://localhost:1087"
git config --global https.proxy "socks5://localhost:1086"
git config --global http.proxy "socks5://localhost:1086"
```

**Comment by lvgithub** [comment]
Build Fails,maybe also run

`git submodule update --init` in the v8worker2 dir.
`sudo apt-get install libgtk-3-dev pkg-config ccache` on ubuntu
`sudo yum install libgtk-3-dev pkg-config ccache` on centos
`sudo brew install libgtk-3-dev pkg-config ccache` on macOS

**Comment by D8Ge** [comment]
@JieJiSS  i had try it, not work!

**Comment by JieJiSS** [comment]
@D8Ge I have https://github.com/shadowsocks/ShadowsocksX-NG installed and have a working proxy server.
However you don't necessarily need to have it installed, other proxy / VPN software can be ok
The main point is to make the bash/zsh to send requests through your proxy so that you can reach those blocked websites.

you can email me and thus we can talk about this issue **in Chinese**. Hope that can help you understand.

**Comment by D8Ge** [comment]
the problem is build.py need python2, not python3! thinks, @JieJiSS
