### ISSUE TITLE
Import Syntax | From First

### ISSUE THREAD

**Issue by spottedmahn** [ry/deno#240]
What about `from "./util.ts" import { log }`?  Then we can get autocomplete/intellisense 😉

Reference:

![image](https://user-images.githubusercontent.com/14079228/41232634-fa99f632-6d54-11e8-87d0-0ec8313ee54a.png)

**Comment by ry** [comment]
Is that supported syntax? I don't understand.

**Comment by ZanderBrown** [comment]
I can't find any reference to that syntax (it is, of course, similar to python)

**Comment by gillchristian** [comment]
> Is that supported syntax?

Not, it's not,

I don't understand why changing the order of the import statement would enable autocomplete/intellisense?

Anyways, it would require a change in the language so it's out of scope.

**Comment by ry** [comment]
Closing this issue.

Please let's try to keep the issues as quiet as possible. It makes it difficult for me to give attention to important matters.

**Comment by spottedmahn** [comment]
>I don't understand why changing the order of the import statement would enable autocomplete/intellisense?

B/C then tools like VS Code know the library/module so it can provide auto-complete on the `import`

**Comment by monkingxue** [comment]
@ry If we write the the path of deps using `from` before `import`, the tools can complete the name of exports for us easily.

**Comment by TomasHubelbauer** [comment]
While it's true that this would enable autocomplete, I don't see how it makes sense to open this issue in Deno. This should go to TypeScript, where there probably already exists a rejected issue for this - because this is not valid JavaScript and TypeScript doesn't like introducing concepts not backed by JS (just ask about `nameof`).

**Comment by ZanderBrown** [comment]
VSCode autocompletes successfully, just fill in the {} after giving the path

**Comment by kitsonk** [comment]
> B/C then tools like VS Code know the library/module so it can provide auto-complete on the `import`

This has been discussed multiple times in the context of TypeScript and every time, the TypeScript team has responded that variation from the TC39 standard is a non-goal of TypeScript.  That should be a non-goal of deno as well, not inventing any language syntax.

If you don't like the way the language is designed, the right channel is to focus on discussing that with TC39/ECMAScript, but I am 99% sure you won't get very far, because again, it has been discussed multiple times.  It _might_ have been a mistake, but it is what it is since it was ratified in 2015.

**Comment by spottedmahn** [comment]
>That should be a non-goal of deno as well, not inventing any language syntax.

That makes sense.  Really appreciate response @kitsonk!  Thanks 🙏!
