### ISSUE TITLE
Avoiding 10 future regrets for deno

### ISSUE THREAD

**Issue by jorangreef** [ry/deno#241]
@ry Thanks for deno! Your goals for deno are spot on.

Just wanted to share some thoughts I've had working with Node.

1. Interfaces should allow for zero-copy and leave memory allocation to the user as much as possible, e.g.  suppose deno ever adds a core crypto api (and hopefully it never will!), but then a cipher method would allow the user to pass in not just a source buffer, but also a target buffer and a target buffer offset.

2. Ideally, sockets should never allocate buffers, streams should always be pull-only (instant flow control that way), and reading from a stream should always support reading into a user-supplied target buffer (at a target offset).

3. Propagate the idea of a single-threaded event loop control plane with a multi-core data plane, much more than Node has done. Node has sometimes had a tendency to conflate the two, so people end up doing [all their crypto in the event loop](https://github.com/nodejs/node/issues/678#issuecomment-370193050) without regard to throughput. Sometimes it makes sense to avoid threadpool overhead (e.g. hashing 32 bytes shouldn't be in the threadpool), but most of the time things like base64, hex, string encoding etc. should be able to run in the threadpool where it makes sense (e.g. decoding a 10 MB base64 MIME attachment), and should be async by default.

4. Make deno [a superset of all supported platforms](https://nodejs.org/en/docs/guides/working-with-different-filesystems/), not a leaky lowest-common-denominator. Node has sometimes wanted to normalize things across platforms far too much (e.g. force Unicode NFC everywhere - bad idea), or been slow to add file `btime` setters on platforms that support it, just because other platforms didn't. Something as simple as setting `ulimit` on Linux is just not possible with Node out of the box because of this kind of LCD thinking. Electron for all its faults is a good example of exposing platforms as they really are.

5. Personally, I think Rust will be better than Go down the line for native bindings. One GC in v8 is enough!

6. Keep the core small. Native add ons are the way to go. Node's N-API is actually brilliant here.

Actually, that's it. Avoiding 6 future regrets should be enough!

**Comment by ry** [comment]
@jorangreef Thank you for voicing these. I agree with you everywhere.

> Interfaces should allow for zero-copy and leave memory allocation 

Absolutely - it has been a major design goal. Thanks to modern V8 support of ArrayBuffers and protobufs this is very possible.

> sockets should never allocate buffer

I would have disagreed with you years ago, but I do agree now. (I thought to best support Windows was to use IOCP, which preallocates buffers. But these days [fast polling](https://github.com/piscisaureus/wepoll) is available on windows, so it makes sense to expose a non-blocking API and leave the alloc to users.

> Personally, I think Rust will be better than Go down the line for native bindings. One GC in v8 is enough!

Yes, I am also very concerned about the double GC that will come with Go. I'm also concerned with how non-minimal Rust is. I'm still researching it... 

cc @piscisaureus

**Comment by alexhultman** [comment]
> I would have disagreed with you years ago, but I do agree now. (I thought to best support Windows was to use IOCP, which preallocates buffers. But these days fast polling is available on windows, so it makes sense to expose a non-blocking API and leave the alloc to users.

It doesn't make sense to let Windows (a broken down pisshole of an operating system) dictate how all systems should work. Linux is the main operating system used for servers and both Linux and OS X are **reactor** systems while Windows started out as reactor back in the 90s and then also added proactor support.

Proactor aka the act of telling the system "hey, I have this user space buffer of 32kb allocated, please fill it with data whenever you can and tell me when done" means every fucking single socket needs to hold an allocated 32 kb user space buffer at all fucking times.

With reactor, **no buffers are needed** as you instead get an event when you have data to be read from the system. This means you can have a shared user space buffer, and this buffer can be 512 kb large meaning you can read more data per syscall thus get greater throughput.

Also, Linux **is not natively a proactor system** meaning any wrapper that pretends Linux is a proactor (ASIO, libuv, etc.) is simply fooling itself and not achieveing anything other than bloat and lower thoughput.

The way Linux is supposed to be used, as is properly demonstated in µSockets, µWebSockets and MIO and ws-rs and those projects and also lwan, etc. is like described. It requires tons of gigabytes of less memory simply put and is faster.

And since Windows is, has been and still is **both** reactor and proactor. It makes no sense to select proactor as the model. I can hold millions of websockets using a total of 100 mb of user space memory. Why? Because of the proper use of **reactor** model on a **reactor system**.

**Comment by alexhultman** [comment]
If you want something done reasonably well and for Rust, just use MIO: https://github.com/carllerche/mio

MIO is used by ws-rs which is the top most performing contender to µWS and beats every other candidate in every single aspect.

Tokio which another user talked about does up to 2 million req/sec and makes use of MIO.

Selecting the total miscarriage of a library libuv as networking implementation is literally the worst possible repeated mistake that can be done. I have hated it for 2 years straight and had to reimplement everything it does from scratch just to get my results.

**Comment by piscisaureus** [comment]
@jorangreef 

> Interfaces should allow for zero-copy and leave memory allocation to the user as much as possible, e.g. suppose deno ever adds a core crypto api (and hopefully it never will!), but then a cipher method would allow the user to pass in not just a source buffer, but also a target buffer and a target buffer offset.
> Ideally, sockets should never allocate buffers, 
> and reading from a stream should always support reading into a user-supplied target buffer (at a target offset).

While I am fairly sympathetic to this idea, a few counterpoints the record.
* "Reading into a user-supplied target buffer" and "zero-copy" are somewhat at odds with one another, in particular when it comes to javascript. It works when we can do poll + nonblocking read/write, but once we have to do something in the thread pool (e.g. crypto, gzip, filesystem I/O), it means that buffer contents are going to be modified by a different thread, and if the buffer is user-specified this effect becomes directly observable. The v8 people always told me that what node is doing is technically against its API rules (although it works in practice), and TC39+DOM standards people have traditionally resisted APIs which would make multithreading effects observable (although nowadays there's SharedArrayBuffer so maybe this is no longer that relevant.)
* In libuv, we made the user responsible for allocating memory that libuv used to store "internal" state associated with a handle (e.g socket, timer, etc). This is somewhat nice because it reduces the number of heap allocations, but it also makes the API very leaky. Now the user needs to know how much space libuv needs, and if libuv changes something about how it manages state internally, this immediately becomes an API/ABI changes. In hindsight I regret this decision.

> streams should always be pull-only (instant flow control that way), 

Very much yes.

> Propagate the idea of a single-threaded event loop control plane with a multi-core data plane, much more than Node has done. Node has sometimes had a tendency to conflate the two, so people end up doing all their crypto in the event loop without regard to throughput. Sometimes it makes sense to avoid threadpool overhead (e.g. hashing 32 bytes shouldn't be in the threadpool), but most of the time things like base64, hex, string encoding etc. should be able to run in the threadpool where it makes sense (e.g. decoding a 10 MB base64 MIME attachment), and should be async by default.

While I agree that node's support for off-the-main-thread data processing is severely lacking, I am not convinced that moving work to the thread pool is really the solution. A counterexample would be gzip - it can be done in the thread pool in node, now people expect it to be effectively free (see e.g. https://github.com/nodejs/node/issues/8871).

> Make deno a superset of all supported platforms, not a leaky lowest-common-denominator. Node has sometimes wanted to normalize things across platforms far too much (e.g. force Unicode NFC everywhere - bad idea), or been slow to add file btime setters on platforms that support it, just because other platforms didn't. Something as simple as setting ulimit on Linux is just not possible with Node out of the box because of this kind of LCD thinking. Electron for all its faults is a good example of exposing platforms as they really are.

I agree we screwed up a bit in node sometimes (e.g. LCD approach in fs.watch really gave us worst-of-both-worlds). However I stand by our general approach -- trying to reconcile the differences between platforms in order to expose a single API that works everywhere. Otherwise you end up in the situation that software is effectively never portable, because platform-specific APIs sneaks in without the developer being aware of it. It may have taken a while to add `btime`, but if we had done it fast-and-loose then `btime` would have been called `ctime` on windows (hello python, php).

I'll look into what electron does differently.

> Personally, I think Rust will be better than Go down the line for native bindings. One GC in v8 is enough!
> Keep the core small. Native add ons are the way to go. Node's N-API is actually brilliant here.

Agree on all that!

**Comment by alexhultman** [comment]
Libuv docs aren't exactly reactor:

void (*uv_alloc_cb)(uv_handle_t* handle, size_t suggested_size, uv_buf_t* buf)¶
Type definition for callback passed to uv_read_start() and uv_udp_recv_start(). The user must allocate memory and fill the supplied uv_buf_t structure. If NULL is assigned as the buffer’s base or 0 as its length, a UV_ENOBUFS error will be triggered in the uv_udp_recv_cb or the uv_read_cb callback.

A suggested size (65536 at the moment in most cases) is provided, but it’s just an indication, not related in any way to the pending data to be read. The user is free to allocate the amount of memory they decide.

As an example, applications with custom allocation schemes such as using freelists, allocation pools or slab based allocators may decide to use a different size which matches the memory chunks they already have.

Example:

static void my_alloc_cb(uv_handle_t* handle, size_t suggested_size, uv_buf_t* buf) {
  buf->base = malloc(suggested_size);
  buf->len = suggested_size;
}

This doc very clearly talks about actually allocating memory for each can and looking at Node.js sources for stream wrap shows a completely messed up data flow where if I understand things you call into JavaScript to allocate a JavaScript buffer which is just mind-blowing. If done correctly you would have absolutely zero allocations for this flow. That's the point of my rant.

**Comment by jorangreef** [comment]
> Personally, I think Rust will be better than Go down the line for native bindings. One GC in v8 is enough!

I still think the GC in Go is not ideal, but then again Rust's syntax is not the most RSI friendly. Zig might be the sweet spot: https://github.com/ziglang/zig/wiki/Why-Zig-When-There-is-Already-CPP%2C-D%2C-and-Rust%3F

**Comment by rayfoss** [comment]
Funny that this came up when I searched for Flow... Flow is a better typed Js then Typescript. The TS choice is a regret in the making

**Comment by zhaoyao91** [comment]
@rayfoss I like flow, but its ecosystem and supports are far less than ts.

**Comment by mattyclarkson** [comment]
> Native add ons are the way to go

It'd be brilliant if deno native modules are WASM with WASI. Then we free up the ecosystem to use various languages for the plugins.

**Comment by alevosia** [comment]
> Funny that this came up when I searched for Flow... Flow is a better typed Js then Typescript. Forcing TS support is a regret in the making

How's flow?
